name: Release

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub
        uses: actions/checkout@v2

      - name: Get Version
        run: |
          echo VERSION=$(cat ProxerExport.meta.js | grep version | cut -d ' ' -f 7) >> $GITHUB_ENV

      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}